### PR TITLE
Many UI Tweaks

### PR DESCRIPTION
**Pull request by skyguy126**
- Preload app icons to make list scrolling smooth
- removed unnecessary refreshes
- fixed settings saving
- fixed crash when app does not have a launch activity
- other minor ui tweaks
- code cleanup

UI is much smoother overall.

### CODE REVIEW

**Comment by chiehmin** [comment]
It seems like an amazing update! I will review it later.

BTW, I will list you as an contributor in the README. You are the contributor who contribute the most in code since MinMinGuard is created. 👍

**Comment by skyguy126** [comment]
Thank you, please let me know if you have any questions. 👍

**Comment by skyguy126** [comment]
@chiehmin Added a minor update, changelog in commit message

**Comment by chiehmin** [comment]
Thank you! It is a amazing improvement :)

**Comment by chiehmin** [comment]
I found a bug according to this PR. When switching between modes(ex: from whitelist mode to blacklist mode), the settings does not load automatically. I have to refresh manually. Can you help me to fix it :) ?

**Comment by skyguy126** [comment]
@chiehmin I'll look into it, thanks for letting me know.

**Comment by chiehmin** [comment]
@skyguy126 BTW, I added a contributor section into the README. If you want to update your information, just update it and send me a PR :).

**Pull request merged**
