### PR TITLE
Fix NullPointerExceptions when using Youtube app

### PR DESCRIPTION
**Pull request by mh0rst**
When using MinMinGuard 2.0beta5 with set to Auto together with Youtube app version 12.44.53, the Xposed log would be spammed with NPEs occurring in the NameBlocking hook.

This fixes it for me.

### CODE REVIEW

**Comment by wanam** [comment]
More information about the issue: https://github.com/wanam/YouTubeAdAway/issues/33#issuecomment-343411609

**Comment by Grossdm** [comment]
@mh0rst it looks like you may have fixed this issue.
Has the dev been at all active with this?
If not, would you consider making your fork available via Xposed?

Just some thoughts and hopes for this module.
It has been wonderful! I'd hate to see it decline.

TIA

**Comment by chiehmin** [comment]
Hi, thanks for your wonderful fix. I am pretty busy with my current life and I have no time continuing maintaining this project :(

You are welcome to fork it and further develop it and I will make a link to your new project :)

**Comment by mh0rst** [comment]
As an active user and huge fan of this module, I will make sure it will continue to work - at least on my device with latest Xposed and the (few) applications I am using.
However, I too am currently busy (preparing my master's thesis) and can spend only little time on this module. Maintaining my own fork with support for apps I don't have is currently out of reach for me.

Publishing the fix to Xposed repo would require a change of package name, signature and maybe even module name, for which I don't have time atm. For now, I published the fixed APK here: https://github.com/mh0rst/MinMinGuard/releases/tag/v2.0b6
Just watch my repository if you wish to be informed about updates.

**Pull request merged**
