### PR TITLE
Added setting to hide launcher icon, added new icon

### PR DESCRIPTION
**Pull request by skyguy126**
Designed and added a new icon, added a setting to hide the app icon from the launcher.

### CODE REVIEW

**Comment by chiehmin** [comment]
Wow, it seems great! Gonna review it later. Thanks!

**Comment by chiehmin** [comment]
Merged! Thanks for your contribution 👍

**Comment by chiehmin** [comment]
Hi, I have released MinMinGuard v2.0 beta5. I just want to say thank you again for your great contribution. Looking forward to see your great contribution again :)

**Comment by skyguy126** [comment]
No problem 👍

**Pull request merged**
