### PR TITLE
Added Avocarrot ad network (last unblocked ad on Casper)

### PR DESCRIPTION
**Pull request by elton235**
Added the Avocarrot ad network, in order to block an ad that pops up in Casper after you send a Snap.

### CODE REVIEW

**Comment by chiehmin** [comment]
This is great! However, I recently add some more helper function in [ApiBlocking](https://github.com/chiehmin/MinMinGuard/blob/master/app/src/main/java/tw/fatminmin/xposed/minminguard/blocker/ApiBlocking.java) file. Could you change to use `removeBanner` and `blockAdFunction`? I will refactor all ad network blockers to use them in near future. Here's an [example](https://github.com/chiehmin/MinMinGuard/blob/master/app/src/main/java/tw/fatminmin/xposed/minminguard/blocker/adnetwork/MobFox.java).

**Comment by chiehmin** [comment]
And I think for Interstitial type ads. You just need to call `blockAdFunction` instead of `removeBanner`.

**Comment by elton235** [comment]
It looks like Casper has stopped using Avocarrot, at least for the time being. I don't have any way of testing anymore. If the Avocarrot ads come back, I'll make the changes you suggested.

**Comment by elton235** [comment]
Scratch that, I found a great testing app:
https://github.com/Avocarrot/android-demo-app

I'll go through it and all all their different types of ads. :)

**Comment by chiehmin** [comment]
Great!

**Comment by elton235** [comment]
Casper's back to using Avocarrot, so I finally got to test it on that.

**Comment by chiehmin** [comment]
The PR looks good. Thanks :)

**Pull request merged**
