### PR TITLE
Patched a bunch of Blockers. Added some easy debug messages

### PR DESCRIPTION
**Pull request by MSkjel**

### CODE REVIEW

**Comment by chiehmin** [comment]
Greate job. Thank you. BTW, do you want to take over MinMinGuard's future development? I would like to include you as a collaborator.

**Comment by MSkjel** [comment]
Sure, I'd love to. Could you also add me as an author on the Xposed module repo, so I can release new versions?

**Comment by chiehmin** [comment]
It's a good news to hear you would like to take over the future development :). I've invited you to be a collaborator of MinMinGuard on Github.

I would also like add your XDA id as an author on Xposed repository. And I will made an announcement on the XDA thread. You can leave your XDA id in this thread.

Thank you :+1:

**Comment by MSkjel** [comment]
XDA id is the same as here on Github, MSkjel

**Comment by chiehmin** [comment]
@MSkjel You should also register on [XDA repo](https://repo.xposed.info/). I can only add you as an author after you register.

**Comment by MSkjel** [comment]
I am already registered on the Xposed repo

**Comment by chiehmin** [comment]
@MSkjel I have added you on Xposed Repo. Please check it :)

**Comment by chiehmin** [comment]
@MSkjel To release a new version of MinMinGuard. Just simply add a tag and push to the Github which will trigger the Travis CI to build a new version of MinMinGuard and use the deployment keystore to sign the APK. And the APK will be show on the [release page](https://github.com/chiehmin/MinMinGuard/releases) automatically.

**Comment by chiehmin** [comment]
I have made a announcement on the [XDA thread](https://forum.xda-developers.com/showpost.php?p=79107464&postcount=2014).
Please continue your great work and wish you the best :+1:

**Pull request merged**
